services:
  qwen-bench:
    build:
      dockerfile: docker/rocm.Dockerfile
      context: ..
    container_name: qwen-bench-rocm
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "8000:8000"
    ipc: host
    tty: true
    stdin_open: true
    command: fish
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    restart: unless-stopped
