defaults:
  - model: qwen2_5vl_7b
  - data: pseudo_camera
  - training: nvidia
  - theme: nord
  - _self_

stage: train
with_data: false

paths:
  data_dir: /data/ekvirival
  output_dir: ./output
  hf_home: /data/ekvirival/.cache
  hf_datasets_cache: /data/ekvirival/.cache/datasets

seed: 42

hydra:
  job:
    chdir: false
  run:
    dir: .
  output_subdir: null
